name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Cache Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-repository-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Build Project
        run: mvn --batch-mode --update-snapshots verify

      - name: Publish to GitHub Packages
        run: mvn --batch-mode --settings $GITHUB_WORKSPACE/settings.xml deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
